#!/bin/bash

update=0
case "$1" in
	--update-expected|-u)
		update=1
		shift
	;;
esac

if [ -z "$1" ]; then
	echo "Usage: $0 [-u|--update-expected] <program>"
	exit 1
fi

program="$(realpath "$1")"

testdir="$(dirname "$0")"

passed=0
failed=0

pass() {
	echo -e "\r[\033[1;32mPASS\033[m]"
	((passed++))
}

fail() {
	echo -e "\r[\033[1;31mFAIL\033[m]"
	((failed++))
}

set -e

rm -rf test-output test-diff
mkdir test-output test-diff
ln -sfT "$testdir/tests" tests

set +e

for t in "tests"/*; do
	t=${t##*/}
	echo -n "[....] $t"
	if [ $update == 0 -a ! -f "$testdir/expected/$t" ]; then
		echo -e "\r[\033[1;34m????\033[m] $t - not run - expected output unavailable"
	else
		$program tests/$t &> "test-output/$t"
		r=$?
		if [ $r != 0 ]; then
			fail
			echo "Program exited with non-zero status code ($r)"
		elif [ $update == 1 ]; then
			pass
			cp "test-output/$t" "$testdir/expected/$t"
		elif git --no-pager diff -U1 --no-index --color --exit-code "test-output/$t" "$testdir/expected/$t" > "test-diff/$t.diff"; then
			pass
		else
			fail
			tail -n+5 test-diff/$t.diff
		fi
	fi
done

if [ $failed == 0 ]; then
	echo -e "[\033[1;32mALL $passed TESTS PASSED\033[m]";
	exit 0
else
	echo -e "[\033[1;31m$failed TEST(S) FAILED\033[m]";
	exit 1
fi
